### ISSUE TITLE
Example in testing section does not work

### ISSUE THREAD

**Issue by smfx** [rerun-io/ewebsock#40]
Hi!

1. I start echo server with: `cargo r -p echo_server`
2. Then I start the native example: `cargo run -p example_app`
3. I see the connection both on client:
![image](https://github.com/user-attachments/assets/578534b8-94f0-44c7-b51f-6f988e4dbe95)

and on server:
 ```➜  ewebsock git:(main) cargo r -p echo_server
   Compiling echo_server v0.1.0 (/home/smfx/tmp/ewebsock/echo_server)
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/echo_server`
Listening on: ws://127.0.0.1:9001
New client connected
```

4. When I send any message nothing happens. I don't see anything in server logs nor in client app.

I checked on rust 1.79 and 1.76.

**Comment by jovisnj** [comment]
Hi.

I can confirm this as well. I also tried connecting the `example_app` to a websocket server other than the `echo_server` provided in the examples, and it behaves the same. The connection is established, but then messages don't arrive to the server side. If I try an alternative client implementation and connect it to the example `echo_server`, messages do get through. So I presume something is wrong with the `example_app`.

**Comment by emilk** [comment]
This broke with the recent update to tungstenite 0.23:

* https://github.com/rerun-io/ewebsock/pull/39

**Comment by Its-Just-Nans** [comment]
I currently see that the example is working

I guess the fix was https://github.com/rerun-io/ewebsock/pull/45

Conclusion: `example_app` is working now
