### ISSUE TITLE
WebSocket Server Reports Unexpected EOF on Connect, but ewebsock Returns Ok

### ISSUE THREAD

**Issue by danforbes** [rerun-io/ewebsock#5]
I'm trying to connect to the WebSocket server exposed by a [Polkadot](https://github.com/paritytech/polkadot) node. Here is my code:

```rs
#[tokio::main]
async fn main() {
    let mut ws = match ewebsock::connect("ws://100.115.92.194:9944") {
        Ok(ws) => ws,
        _ => panic!("Cannot connect to WebSocket server"),
    };

    ws.0.send(WsMessage::Text(
        "{ \"id\": \"metadata\", \"method\": \"state_getMetadata\", \"jsonrpc\": \"2.0\" }"
            .into(),
    ));

    while let Some(event) = ws.1.try_recv() {
        println!("{:?}", event);
    }
}
```

The program terminates without exception, but does not print anything either. In the logs of the Polkadot node, I see the following message:

```
Rejected connection: Transport(i/o error: unexpected end of file

Caused by:
    unexpected end of file)
```

Is this due to user error?

**Comment by danforbes** [comment]
Looks like other people are seeing this error when connecting to Polkadot nodes as well. I am only seeing the problem when I try to connect from this library (the connection works fine from a JavaScript [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) instance).

**Comment by emilk** [comment]
By using `try_recv`, you will stop looping as soon as there is no message (which is likely right away). This means you will never actually get back an answer, and the connection will drop immediately. This _could_ be part of the answer.

Is this on native or web btw?

**Comment by danforbes** [comment]
> ...you will stop looping as soon as there is no message (which is likely right away).

Yes, I thought this may be the problem, but I didn't see any examples or anything that demonstrated other ways to explore the capabilities of this library.

I am running this natively.

**Comment by emilk** [comment]
>  I didn't see any examples

https://github.com/rerun-io/ewebsock/blob/main/example_app/src/app.rs
