### ISSUE TITLE
you cannot `trunk serve` the example app out of the box

### ISSUE THREAD

**Issue by duckfromdiscord** [rerun-io/ewebsock#9]
There is no `index.html` for `trunk` to use when you first clone this repo. To build the example app for WASM, `trunk` requires an index.html and a couple dependencies. There seems to be some functionality in the code already for WASM but it is unfinished and we cannot build for WASM.

This change here makes it so that you can clone the repo, move into the example app folder, and `trunk serve` right away: https://github.com/duckfromdiscord/ewebsock/commit/0b7938d0411f1b8048b2b687c3a3d00202a02a67

**Comment by emilk** [comment]
Feel free to make a PR to make it easy to compile with trunk

**Comment by emilk** [comment]
* Closed by https://github.com/rerun-io/ewebsock/pull/38
